In [1]:
import numpy as np

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [2]:
a=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
a.shape

(3, 4)

In [4]:
a.size

12

In [5]:
a.ndim

2

4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
a=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [8]:
a=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a[2][3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
a=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
odd_indexed_elements=a[:,1::2]
odd_indexed_elements

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [20]:
a=np.random.rand(3,3)
a

array([[0.11811515, 0.62407811, 0.53780199],
       [0.23504548, 0.05123847, 0.60887963],
       [0.03315208, 0.55184391, 0.23425183]])

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [21]:
a=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
np.expand_dims(a,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [25]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:
Matrix A [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python
1. Index wise multiplication
2. Matix multiplication
3. Add both the matices
4. Subtact matix B from A
5. Diide Matix B by A

In [27]:
A=np.matrix([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
B=np.matrix([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

In [29]:
A

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [30]:
B

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [31]:
A*B

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [32]:
A@B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [33]:
A+B

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

In [34]:
A-B

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [36]:
A/B

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
a.shape

(3, 4)

In [40]:
np.reshape(a,(4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
15. What is broa^casting in Numpy?